### ISSUE TITLE
full wave bridge inverter output issue

### ISSUE THREAD

**Issue by UmerArain** [upb-lea/awesome-open-source-power-electronics#1]
hello sir i have an issue i am going to operate full wave bridge inverter module you can see in fig; i gave a pwm signal at drive IC IR2110 4.5 Voltage at HI OR LOW side input through arduino and 12 volt supply from external source at regulator IC output it shows voltages 10volt which is enough to drive igbts and i want to see output AC at sink its not show any output or at any igbts please help me about this moudule
this is code i have to used for arduino pwm signal
int outputPin = 3;
int outputpin1 = 5;
void setup()
{
pinMode(outputPin,OUTPUT);
pinMode(outputpin1,OUTPUT);
}

void loop()
{
analogWrite(outputPin,230); //change 255 to any value between 0-255
delay(100);
analogWrite(outputpin1,230
![WhatsApp Image 2022-04-07 at 11 07 49 AM](https://user-images.githubusercontent.com/88420976/162135388-9cbdb669-c66d-48ad-8092-9e3623d3e705.jpeg)
); //change 255 to any value between 0-255
delay(100);
}
Thankyou

**Comment by gituser789** [comment]
This issue does not fit this repository.
