### ISSUE TITLE
How about the tool eSim?

### ISSUE THREAD

**Issue by Eyantra698Sumanto** [upb-lea/awesome-open-source-power-electronics#2]
How about the tool eSim? @gituser789 @MohanNagella 

1. https://github.com/FOSSEE/eSim
2. https://esim.fossee.in/home

Expecting your quick response.

**Comment by gituser789** [comment]
Hi, 
thanks for your hint.
Can you tell how it is used for `power electronics` simulation?
What are the typical use-cases and how are transistor losses (conduting/switching losses) calculated?

I am looking for the connection to `power electronics`.

**Comment by Eyantra698Sumanto** [comment]
Hi,

There are components like SCR, TRIAC, Power Diode, Transformer, switches etc. One can easily built a Power Electronics circuit. Moreover eSim is built using Ngspice. So all the features available in SPICE simulation are present in eSim. It will be great if you could include it. Please feel free to contact us.

Regards, 
Sumanto Kar

**Comment by Eyantra698Sumanto** [comment]
@gituser789 

Please have a look at the following websites:
1.https://static.fossee.in/esim/manuals/eSim_Manual_2.3.pdf
2. https://esim.fossee.in/circuit-simulation-project
3. https://esim.fossee.in/lab_migration_run/30

**Comment by Eyantra698Sumanto** [comment]
@gituser789 Also eSim is made using KiCad as the frontend...
