### ISSUE TITLE
ElmerFEM

### ISSUE THREAD

**Issue by jvencels** [upb-lea/awesome-open-source-power-electronics#7]
ElmerFEM is a highly parallelized 2D and 3D FEM software with models and templates for magnetic simulations. It can solve cases with harmonic and transient excitations and provides models for massive/foil/stranded wires and core loss calculations.

https://github.com/ElmerCSC/elmerfem
https://www.elmerfem.org/forum/

![T_white_34](https://user-images.githubusercontent.com/5177281/221803717-d5a80719-61f5-4cc4-8f7f-0d698ff3659a.png)

**Comment by jvencels** [comment]
Hello again,

Thank you for updating the information. 
May I suggest you use a different picture, for example, the one I shared? That simulation was produced by ElmerFEM.
The picture that was taken from the EOF-Library (I am also the author for it :)) page is outdated and is not relevant for power electronics engineers as it is more abstract.

Thanks!

**Comment by gituser789** [comment]
Done :)
